# Generated by Django 4.0.2 on 2022-02-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mentee', models.BooleanField()),
                ('is_mentor', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.businessarea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='description',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendance_status',
            field=models.CharField(choices=[('GA', 'going_ahead'), ('C', 'cancelled')], max_length=10),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.BooleanField()),
                ('active_status', models.CharField(choices=[('A', 'active'), ('I', 'inactive')], max_length=10)),
                ('advertising_for_group', models.BooleanField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
            ],
        ),
        migrations.CreateModel(
            name='POATarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('completed_status', models.CharField(choices=[('I', 'incomplete'), ('C', 'complete')], max_length=10)),
                ('plan_of_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.planofaction')),
            ],
        ),
        migrations.AddField(
            model_name='planofaction',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.relationship'),
        ),
        migrations.AddField(
            model_name='planofaction',
            name='set_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile'),
        ),
        migrations.CreateModel(
            name='MentorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_mentee', to='mentoring.profile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_mentor', to='mentoring.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeAttending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.relationship')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_hour', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAreaChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(max_length=10)),
                ('new_business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.businessarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BecomeMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.profile')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='relationship',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mentoring.relationship'),
            preserve_default=False,
        ),
    ]
