# Generated by Django 4.0.2 on 2022-02-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_businessarea_planofaction_profile_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingfeedback',
            name='meeting',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
