# Generated by Django 4.0.2 on 2022-02-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='menteeattending',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='planofaction',
            name='relationship',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
