# Generated by Django 4.0.2 on 2022-02-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0006_relationship_meeting_meetingfeedback_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.relationship'),
        ),
        migrations.AlterField(
            model_name='meetingfeedback',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.meeting'),
        ),
        migrations.AlterField(
            model_name='menteeattending',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.relationship'),
        ),
        migrations.AlterField(
            model_name='planofaction',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.relationship'),
        ),
    ]
