# Generated by Django 4.0.1 on 2022-03-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0007_alter_meeting_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessareachangerequest',
            name='request_status',
        ),
        migrations.AddField(
            model_name='businessareachangerequest',
            name='checked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_area',
            field=models.ForeignKey(choices=[('marketing', 'Marketing'), ('humanresources', 'Human Resources'), ('finance', 'Finance'), ('technology', 'Technology'), ('strategy', 'Strategy'), ('operations', 'Operations')], on_delete=django.db.models.deletion.CASCADE, to='mentoring.businessarea'),
        ),
    ]
