# Generated by Django 4.0.2 on 2022-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0008_meetingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingfeedback',
            name='meetingtitle',
            field=models.TextField(default='Meeting Name Unavailiable'),
        ),
    ]
