# Generated by Django 4.0.1 on 2022-03-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0009_alter_businessareachangerequest_user_meetingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessareachangerequest',
            old_name='user',
            new_name='profile',
        ),
    ]
