# Generated by Django 4.0.1 on 2022-03-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0010_rename_user_businessareachangerequest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorskill',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_of_expertise', to='mentoring.profile'),
        ),
    ]
