# Generated by Django 4.0.2 on 2022-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0010_remove_poatarget_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planofaction',
            name='finish_date',
            field=models.DateTimeField(),
        ),
    ]
