# Generated by Django 4.0.1 on 2022-03-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0011_alter_mentorskill_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeinterest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_of_interest', to='mentoring.profile'),
        ),
    ]
