# Generated by Django 4.0.1 on 2022-03-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0012_alter_menteeinterest_mentee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomementor',
            old_name='user',
            new_name='profile',
        ),
    ]
