# Generated by Django 4.0.2 on 2022-03-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0011_alter_planofaction_finish_date'),
        ('mentoring', '0013_rename_user_becomementor_profile'),
    ]

    operations = [
    ]
